TEST_VALUE:
  name: dev_cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4ca52c46378100e
  FEISHU_APP_SECRET: UlD0XUOxGbNlWCq9TbfPyftEeHrPy3WT
